### ISSUE TITLE
Warnings related to mechanism file

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem2#259] opened 2017-11-21 20:00 UTC
1. The MCM usually uses `D` to indicate the exponential but sometimes uses `E`. This results in a number of compilation warnings about single precision constants.

2. Sometimes the MCM extractor breaks long lines like this:

```
% 8.8D-12*EXP(-1320/TEMP) + 1.7D-14*EXP(423/TEMP) : CH3COCH3 + OH =
 CH3COCH2O2 ;% J<21> : CH3COCH3 = CH3CO3 + CH3O2 ;
```

These are problems with the web extractor and/or the MCM database, but need to make sure they are not problem for the python scripts and the compiler and they do not affect the model results.

**Comment by rs028** [comment] 2018-05-09 14:19
More info on the second point. The files downloaded from the MCM website seem to use a mixture of Line Feed and Carriage Return. This is apparent when using a text editor that shows new line characters.

For example emacs shows:
```
% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))@0.5*RO2*0.2 : C6H5CH2O2 = BENZAL^M
;^M% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))@0.5*RO2*0.6 : C6H5CH2O2 = C6H5CH2O ;
```

Where `^M` are the Carriage Return characters. Parsing the file as is with the python scripts gives the correct result. In `mechanism-rate-coefficients.f90`:
```
p(2) = 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))**0.5*RO2*0.2   !% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))@0.5*RO2*0.2 : C6H5CH2O2 = BENZAL ;
p(3) = 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))**0.5*RO2*0.6   !% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))@0.5*RO2*0.6 : C6H5CH2O2 = C6H5CH2O ;
```

However if the ^M are removed (for example if the mechanism file is modified and the text editor applies consistent new line characters on saving the file) the python script fails:
```
p(2) = 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))**0.5*RO2*0.2   !% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))@0.5*RO2*0.2 : C6H5CH2O2 = BENZAL ;% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))**0.5*RO2*0.6   !% 2*(KCH3O2*2.4D-14*EXP(1620/TEMP))@0.5*RO2*0.6 : C6H5CH2O2 = C6H5CH2O ;
```

Presumably, the error affects all the files generated by the build scripts because the `fac` file is not parsed  correctly.

**Comment by spco** [comment] 2018-10-29 14:28
This is fixed by #352. Because we can't handle arbitrarily broken files, once it gets a bit unclear how to rectify the file, the script will instead abort and point the user to the line it can't handle. The user can manually edit that line or those around it and re-run the script.

An example would be 
```
% 7.81D-11 : OH = O2 ; %1.00D-12
*7.0 : O2 = NO2 ;
* comment here ;
```
it's actualy incredibly hard to tell the parser that the first lining beginning with `*` is not a comment. In the end, it's easier to let a human handle the non-trivial cases.

**Closed by spco** 2018-10-29 14:28 UTC
Labels: bug, testing

**Comment by rs028** [comment] 2018-10-29 14:40
This should be fine. The error this should fix is described in (https://github.com/AtChem/AtChem2/issues/259#issuecomment-387754651) and it is caused by the web extractor on the MCM website. If that is fixed, than any other type of error should be sorted out by the user.

**Comment by spco** [comment] 2018-10-29 14:43
Yes, I've confirmed that it fixes that. Essentiallly, when more than 2 lines get caught up into a mess together, it gives the error.
