### ISSUE TITLE
Why it says not constrained although I constrained J4

### ISSUE THREAD

**Issue by tanzinaakther** [AtChem/AtChem2#503] opened 2023-09-06 16:36 UTC
Hi, I have constrained photolysis rate but when I run the model, I see the attached note. that means, photolysis rate is not constrained. I checked everything. J1 & J4 is there. Still why i get this.
<img width="446" alt="3" src="https://github.com/AtChem/AtChem2/assets/123010272/e6ad70e8-4ec9-4650-ae29-bd53acafb8be">
? any idea?

**Comment by tanzinaakther** [comment] 2023-09-06 16:36
<img width="582" alt="1" src="https://github.com/AtChem/AtChem2/assets/123010272/5834d604-c942-49ad-b6f1-eba5ff459eb1">

**Comment by tanzinaakther** [comment] 2023-09-06 16:36
<img width="662" alt="2" src="https://github.com/AtChem/AtChem2/assets/123010272/c36b3678-acdb-4522-ac00-7b862e95962a">

**Comment by rs028** [comment] 2023-09-07 09:27
Does the executable point to the right directory?

**Comment by tanzinaakther** [comment] 2023-09-07 15:31
Yes

**Comment by tanzinaakther** [comment] 2023-09-07 15:33
Please see attached. I am getting the output but model is not getting J4 
<img width="768" alt="1" src="https://github.com/AtChem/AtChem2/assets/123010272/217a31f9-d3e0-45e9-ac67-5eaa7b06e616">

**Comment by rs028** [comment] 2023-09-07 16:48
Is the model constrained to J1?

**Comment by tanzinaakther** [comment] 2023-09-07 16:49
Yes. J1 & J4 is constrained

**Comment by rs028** [comment] 2023-09-07 16:53
You have J1 and J4 in the `photolysisConstrained.config` file and the related files in `constraints/photolysis/`.
Is the model reading and constraining J1? or neither?

**Comment by tanzinaakther** [comment] 2023-09-07 16:55
Yes, I have. I attached screenshot in the previous comments that I have these in proper directory. Model is not constraining J1 & J4. It says no photolysis constraints file exist although it is there.

**Comment by rs028** [comment] 2023-09-07 17:01
do the J1 and J4 files have an extension? sometimes a `.txt` is added if you create them in windows but you can't see if the file manager hides the extension

**Comment by tanzinaakther** [comment] 2023-09-07 17:09
Ok , Right now I can't check. So, I will get back to you after checking

**Comment by rs028** [comment] 2023-09-07 17:14
Okay, please close the issue if the problem is solved.

**Comment by tanzinaakther** [comment] 2023-09-07 18:44
I checked. There is no extension.

**Comment by rs028** [comment] 2023-09-08 10:57
I can't see a reason why this may happen. It works fine on my system. Have you tried to do constrain photolysis rates before? If so, did it work?

**Comment by tanzinaakther** [comment] 2023-09-08 17:11
I faced this issue but one of my friends did in his model, it was ok for him. Can I give you my J1 & J4 so that you can have a look?

**Comment by rs028** [comment] 2023-09-08 17:14
Sure sent it to me by email :  rob.sommariva @ gmail.com

**Comment by tanzinaakther** [comment] 2023-09-08 18:04
Hi, I copied my files to my friend's one and then ran. It worked now. But I don't understand what the problem in my folders was.

**Closed** 2023-09-08 20:20 UTC
